### ISSUE TITLE
`repeated_test` no longer compatible with 3.10

### ISSUE THREAD

**Issue by jonringer** [epsy/od#1]
`repeated_test` relies on `unittest2`, which is longer compatible with python 3.10.

Both packages haven't been maintained in 5 years.

They should be dropped.

I know I made this issue twice already, just doing it for completeness :)

related issues:
- https://github.com/epsy/clize/issues/74
- https://github.com/epsy/sigtools/issues/26

**Comment by epsy** [comment]
Fixed with `repeated_test 2.3.1` & `od 2.0.2`
